* Що це таке?
Це сценарій для індексування вмісту архівів, які записуються на диск чи зберігаються віддалено у формі томів.

* Як він працює?
В теці тому (наприклад, тека, вміст якої ви плануєте записати на CD чи DVD) створюється файл md5sums.txt із відбитками md5 для кожного файлу. Якщо у вас є приватний ключ gpg (і вказаний як типовий в налаштуваннях gpg), цей файл також підписується цим ключем. Так ви зможете пересвідчитись в автентичності то́му в будь-який момент часу в майбутньому. Непідписані відбитки md5 все одно надаються для перевірки цілісности тому архіву.

Окрім цього, повний перелік файлів додається в спеціяльну теку (типово: _contents відносно до теки, з якої запущено сценарій) під назвою, яку ви вказали як ідентифікатор тому.

* Як користуватись?
При типовому налаштуванні, сценарій очікує наявність або можливість створити теку _contents як дочірню від тієї, де він запущений. Отже запускати його треба завжди в батьківській теці до вашої _contents. Першим аргументом ви даєте йому знати місце, де лежить ваш том, приготований до запису (чи перенесення у віддалений архів). Другим — ідентифікатор, під яким ви бажаєте записати цей том. Якщо ідентифікатор не вказано, за ідентифікатор береться назва теки, в якій розміщено ваш том (перший аргмент). Приклад:

 ./prepare.sh Диск_до_запису 0001

Успіху!
